# Generated by Django 4.2.7 on 2023-12-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_chat_user_one_alter_chat_user_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
